program PSP;
{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  System.Types,
  IPPeerServer,
  IPPeerAPI,
  IdHTTPWebBrokerBridge,
  Web.WebReq,
  Web.WebBroker,
  WebModuleUnit1 in 'WebModuleUnit1.pas' {WebModule1: TWebModule},
  PSPEngine in 'PSPEngine.pas',
  PSPParser in 'src\PSPParser.pas',
  dwsComp in 'DWScript\Source\dwsComp.pas',
  dwsArrayElementContext in 'DWScript\Source\dwsArrayElementContext.pas',
  dwsArrayExprs in 'DWScript\Source\dwsArrayExprs.pas',
  dwsArrayIndexOfExprs in 'DWScript\Source\dwsArrayIndexOfExprs.pas',
  dwsArrayMethodKinds in 'DWScript\Source\dwsArrayMethodKinds.pas',
  dwsAssociativeArrays in 'DWScript\Source\dwsAssociativeArrays.pas',
  dwsComConnector in 'DWScript\Source\dwsComConnector.pas',
  dwsCompilerContext in 'DWScript\Source\dwsCompilerContext.pas',
  dwsCompilerUtils in 'DWScript\Source\dwsCompilerUtils.pas',
  dwsConnectorExprs in 'DWScript\Source\dwsConnectorExprs.pas',
  dwsConnectorSymbols in 'DWScript\Source\dwsConnectorSymbols.pas',
  dwsConstExprs in 'DWScript\Source\dwsConstExprs.pas',
  dwsContextMap in 'DWScript\Source\dwsContextMap.pas',
  dwsConvExprs in 'DWScript\Source\dwsConvExprs.pas',
  dwsCoreExprs in 'DWScript\Source\dwsCoreExprs.pas',
  dwsCryptoXPlatform in 'DWScript\Source\dwsCryptoXPlatform.pas',
  dwsCustomData in 'DWScript\Source\dwsCustomData.pas',
  dwsDataContext in 'DWScript\Source\dwsDataContext.pas',
  dwsDateTime in 'DWScript\Source\dwsDateTime.pas',
  dwsDebugFunctions in 'DWScript\Source\dwsDebugFunctions.pas',
  dwsDebugger in 'DWScript\Source\dwsDebugger.pas',
  dwsDynamicArrays in 'DWScript\Source\dwsDynamicArrays.pas',
  dwsEncoding in 'DWScript\Source\dwsEncoding.pas',
  dwsErrors in 'DWScript\Source\dwsErrors.pas',
  dwsEvaluate in 'DWScript\Source\dwsEvaluate.pas',
  dwsExperts in 'DWScript\Source\dwsExperts.pas',
  dwsExprList in 'DWScript\Source\dwsExprList.pas',
  dwsExprs in 'DWScript\Source\dwsExprs.pas',
  dwsExternalFunctions in 'DWScript\Source\dwsExternalFunctions.pas',
  dwsExternalSymbols in 'DWScript\Source\dwsExternalSymbols.pas',
  dwsFileFunctions in 'DWScript\Source\dwsFileFunctions.pas',
  dwsFileSystem in 'DWScript\Source\dwsFileSystem.pas',
  dwsFilter in 'DWScript\Source\dwsFilter.pas',
  dwsCompiler in 'DWScript\Source\dwsCompiler.pas',
  dwsUtils in 'DWScript\Source\dwsUtils.pas',
  dwsXPlatform in 'DWScript\Source\dwsXPlatform.pas',
  dwsStrings in 'DWScript\Source\dwsStrings.pas',
  dwsXXHash in 'DWScript\Source\dwsXXHash.pas',
  Wcrypt2 in 'DWScript\Source\Wcrypt2.pas',
  dwsFunctions in 'DWScript\Source\dwsFunctions.pas',
  dwsSymbols in 'DWScript\Source\dwsSymbols.pas',
  DelegateTestLibModule in 'DWScript\Test\DelegateTestLibModule.pas' {DelegateTestLib: TDataModule},
  dwsXPlatformTests in 'DWScript\Test\dwsXPlatformTests.pas',
  LanguageTestsLAZ in 'DWScript\Test\LanguageTestsLAZ.pas',
  UAlgorithmsTests in 'DWScript\Test\UAlgorithmsTests.pas',
  UAutoFormatTests in 'DWScript\Test\UAutoFormatTests.pas',
  UBigIntegerTests in 'DWScript\Test\UBigIntegerTests.pas',
  UBuildTests in 'DWScript\Test\UBuildTests.pas',
  UCodeDOMTests in 'DWScript\Test\UCodeDOMTests.pas',
  UCOMConnectorTests in 'DWScript\Test\UCOMConnectorTests.pas',
  UCornerCasesTests in 'DWScript\Test\UCornerCasesTests.pas',
  UDebuggerTests in 'DWScript\Test\UDebuggerTests.pas',
  UdwsClassesTests in 'DWScript\Test\UdwsClassesTests.pas',
  UdwsCryptoTests in 'DWScript\Test\UdwsCryptoTests.pas',
  UdwsCSSPackTests in 'DWScript\Test\UdwsCSSPackTests.pas',
  UdwsCustomDataTests in 'DWScript\Test\UdwsCustomDataTests.pas',
  UdwsDataBaseTests in 'DWScript\Test\UdwsDataBaseTests.pas',
  UdwsDateTimeTests in 'DWScript\Test\UdwsDateTimeTests.pas',
  UdwsEncodingTests in 'DWScript\Test\UdwsEncodingTests.pas',
  UdwsFunctionsTests in 'DWScript\Test\UdwsFunctionsTests.pas',
  UdwsGraphicsTests in 'DWScript\Test\UdwsGraphicsTests.pas',
  UdwsIniFileTests in 'DWScript\Test\UdwsIniFileTests.pas',
  UdwsSystemInfoTests in 'DWScript\Test\UdwsSystemInfoTests.pas',
  UdwsTabularTests in 'DWScript\Test\UdwsTabularTests.pas',
  UdwsTimeSeriesTests in 'DWScript\Test\UdwsTimeSeriesTests.pas',
  UdwsUnitTests in 'DWScript\Test\UdwsUnitTests.pas',
  UdwsUnitTestsStatic in 'DWScript\Test\UdwsUnitTestsStatic.pas',
  UdwsUtilsTests in 'DWScript\Test\UdwsUtilsTests.pas',
  UdwsWebLibModuleTest in 'DWScript\Test\UdwsWebLibModuleTest.pas',
  UdwsWebUtilsTests in 'DWScript\Test\UdwsWebUtilsTests.pas',
  UdwsXPlatformTests in 'DWScript\Test\UdwsXPlatformTests.pas',
  UExternalFunctionTests in 'DWScript\Test\UExternalFunctionTests.pas',
  UHTMLFilterTests in 'DWScript\Test\UHTMLFilterTests.pas',
  UInstantiateTests in 'DWScript\Test\UInstantiateTests.pas',
  UJITTests in 'DWScript\Test\UJITTests.pas',
  UJITx86_64Tests in 'DWScript\Test\UJITx86_64Tests.pas',
  UJITx86Tests in 'DWScript\Test\UJITx86Tests.pas',
  UJSCodeGenTests in 'DWScript\Test\UJSCodeGenTests.pas',
  UJSFilterTests in 'DWScript\Test\UJSFilterTests.pas',
  UJSONConnectorTests in 'DWScript\Test\UJSONConnectorTests.pas',
  UJSONTests in 'DWScript\Test\UJSONTests.pas',
  UJSSmartLinkerTests in 'DWScript\Test\UJSSmartLinkerTests.pas',
  UJSTestChromium in 'DWScript\Test\UJSTestChromium.pas',
  ULanguageExtensionTests in 'DWScript\Test\ULanguageExtensionTests.pas',
  ULinqJsonTests in 'DWScript\Test\ULinqJsonTests.pas',
  ULinqTests in 'DWScript\Test\ULinqTests.pas',
  ULocalizerTests in 'DWScript\Test\ULocalizerTests.pas',
  UMemoryTests in 'DWScript\Test\UMemoryTests.pas',
  URTTIExposeTests in 'DWScript\Test\URTTIExposeTests.pas',
  UScriptTests in 'DWScript\Test\UScriptTests.pas',
  USourceUtilsTests in 'DWScript\Test\USourceUtilsTests.pas',
  USpecialTestsRTTI in 'DWScript\Test\USpecialTestsRTTI.pas',
  USymbolDictionaryTests in 'DWScript\Test\USymbolDictionaryTests.pas',
  UTestDispatcher in 'DWScript\Test\UTestDispatcher.pas',
  UTokenizerTests in 'DWScript\Test\UTokenizerTests.pas',
  gethostbyaddr in 'DWScript\Test\WebLib\gethostbyaddr.pas',
  gethostbyname in 'DWScript\Test\WebLib\gethostbyname.pas',
  webrequest in 'DWScript\Test\WebLib\webrequest.pas',
  basic_unnamed in 'DWScript\Test\TimeSeriesLib\basic_unnamed.pas',
  nans in 'DWScript\Test\TimeSeriesLib\nans.pas',
  next in 'DWScript\Test\TimeSeriesLib\next.pas',
  ranges in 'DWScript\Test\TimeSeriesLib\ranges.pas',
  rounding in 'DWScript\Test\TimeSeriesLib\rounding.pas',
  basic_batch in 'DWScript\Test\TabularLib\basic_batch.pas',
  basic_cmp_jit in 'DWScript\Test\TabularLib\basic_cmp_jit.pas',
  basic_cmp_nojit in 'DWScript\Test\TabularLib\basic_cmp_nojit.pas',
  basic_columns in 'DWScript\Test\TabularLib\basic_columns.pas',
  basic_manyops in 'DWScript\Test\TabularLib\basic_manyops.pas',
  basic_ops_jit in 'DWScript\Test\TabularLib\basic_ops_jit.pas',
  basic_ops_nojit in 'DWScript\Test\TabularLib\basic_ops_nojit.pas',
  dup in 'DWScript\Test\TabularLib\dup.pas',
  evaluate_columns in 'DWScript\Test\TabularLib\evaluate_columns.pas',
  lookup_stress in 'DWScript\Test\TabularLib\lookup_stress.pas',
  lookupfield in 'DWScript\Test\TabularLib\lookupfield.pas',
  newcolumns_compute in 'DWScript\Test\TabularLib\newcolumns_compute.pas',
  numfield_default in 'DWScript\Test\TabularLib\numfield_default.pas',
  numfielddef_stress in 'DWScript\Test\TabularLib\numfielddef_stress.pas',
  round_floor_ceil in 'DWScript\Test\TabularLib\round_floor_ceil.pas',
  smape in 'DWScript\Test\TabularLib\smape.pas',
  appinfo in 'DWScript\Test\SystemInfoLib\appinfo.pas',
  memory in 'DWScript\Test\SystemInfoLib\memory.pas',
  registry in 'DWScript\Test\SystemInfoLib\registry.pas',
  ackermann in 'DWScript\Test\SimpleScripts\ackermann.pas',
  aliased_enum in 'DWScript\Test\SimpleScripts\aliased_enum.pas',
  aliased_float in 'DWScript\Test\SimpleScripts\aliased_float.pas',
  aliased_vs_nil in 'DWScript\Test\SimpleScripts\aliased_vs_nil.pas',
  alphanum in 'DWScript\Test\SimpleScripts\alphanum.pas',
  arithmetic in 'DWScript\Test\SimpleScripts\arithmetic.pas',
  arithmetic_div in 'DWScript\Test\SimpleScripts\arithmetic_div.pas',
  assert in 'DWScript\Test\SimpleScripts\assert.pas',
  assert_variant in 'DWScript\Test\SimpleScripts\assert_variant.pas',
  assigned in 'DWScript\Test\SimpleScripts\assigned.pas',
  assigned_funcresult in 'DWScript\Test\SimpleScripts\assigned_funcresult.pas',
  assignments in 'DWScript\Test\SimpleScripts\assignments.pas',
  binary_literal in 'DWScript\Test\SimpleScripts\binary_literal.pas',
  bitwise in 'DWScript\Test\SimpleScripts\bitwise.pas',
  bitwise_sar in 'DWScript\Test\SimpleScripts\bitwise_sar.pas',
  bitwise_shifts in 'DWScript\Test\SimpleScripts\bitwise_shifts.pas',
  bool_combos in 'DWScript\Test\SimpleScripts\bool_combos.pas',
  bool_string in 'DWScript\Test\SimpleScripts\bool_string.pas',
  bool_xor in 'DWScript\Test\SimpleScripts\bool_xor.pas',
  boolean_and in 'DWScript\Test\SimpleScripts\boolean_and.pas',
  boolean_array_of in 'DWScript\Test\SimpleScripts\boolean_array_of.pas',
  boolean_is in 'DWScript\Test\SimpleScripts\boolean_is.pas',
  boolean_optimize in 'DWScript\Test\SimpleScripts\boolean_optimize.pas',
  boolean_or in 'DWScript\Test\SimpleScripts\boolean_or.pas',
  booleans in 'DWScript\Test\SimpleScripts\booleans.pas',
  break_continue in 'DWScript\Test\SimpleScripts\break_continue.pas',
  break_in_except_block in 'DWScript\Test\SimpleScripts\break_in_except_block.pas',
  call_conventions in 'DWScript\Test\SimpleScripts\call_conventions.pas',
  case,
  case_boolean in 'DWScript\Test\SimpleScripts\case_boolean.pas',
  case_break in 'DWScript\Test\SimpleScripts\case_break.pas',
  case_range in 'DWScript\Test\SimpleScripts\case_range.pas',
  case_variant in 'DWScript\Test\SimpleScripts\case_variant.pas',
  case_variant_condition in 'DWScript\Test\SimpleScripts\case_variant_condition.pas',
  casts_base_types in 'DWScript\Test\SimpleScripts\casts_base_types.pas',
  char_in in 'DWScript\Test\SimpleScripts\char_in.pas',
  chinese in 'DWScript\Test\SimpleScripts\chinese.pas',
  class_abstract_method in 'DWScript\Test\SimpleScripts\class_abstract_method.pas',
  class_cast in 'DWScript\Test\SimpleScripts\class_cast.pas',
  class_cast_meta in 'DWScript\Test\SimpleScripts\class_cast_meta.pas',
  class_const in 'DWScript\Test\SimpleScripts\class_const.pas',
  class_const_as_prop in 'DWScript\Test\SimpleScripts\class_const_as_prop.pas',
  class_const2 in 'DWScript\Test\SimpleScripts\class_const2.pas',
  class_const3 in 'DWScript\Test\SimpleScripts\class_const3.pas',
  class_const4 in 'DWScript\Test\SimpleScripts\class_const4.pas',
  class_forward in 'DWScript\Test\SimpleScripts\class_forward.pas',
  class_init in 'DWScript\Test\SimpleScripts\class_init.pas',
  class_inline_declared in 'DWScript\Test\SimpleScripts\class_inline_declared.pas',
  class_method in 'DWScript\Test\SimpleScripts\class_method.pas',
  class_method2 in 'DWScript\Test\SimpleScripts\class_method2.pas',
  class_method3 in 'DWScript\Test\SimpleScripts\class_method3.pas',
  class_method4 in 'DWScript\Test\SimpleScripts\class_method4.pas',
  class_of in 'DWScript\Test\SimpleScripts\class_of.pas',
  class_of_cast in 'DWScript\Test\SimpleScripts\class_of_cast.pas',
  class_of2 in 'DWScript\Test\SimpleScripts\class_of2.pas',
  class_of3 in 'DWScript\Test\SimpleScripts\class_of3.pas',
  class_operator1 in 'DWScript\Test\SimpleScripts\class_operator1.pas',
  class_operator2 in 'DWScript\Test\SimpleScripts\class_operator2.pas',
  class_operator3 in 'DWScript\Test\SimpleScripts\class_operator3.pas',
  class_parent in 'DWScript\Test\SimpleScripts\class_parent.pas',
  class_property in 'DWScript\Test\SimpleScripts\class_property.pas',
  class_scoping1 in 'DWScript\Test\SimpleScripts\class_scoping1.pas',
  class_self in 'DWScript\Test\SimpleScripts\class_self.pas',
  class_selfref in 'DWScript\Test\SimpleScripts\class_selfref.pas',
  class_var in 'DWScript\Test\SimpleScripts\class_var.pas',
  class_var_as_prop in 'DWScript\Test\SimpleScripts\class_var_as_prop.pas',
  class_var_dyn1 in 'DWScript\Test\SimpleScripts\class_var_dyn1.pas',
  class_var_dyn2 in 'DWScript\Test\SimpleScripts\class_var_dyn2.pas',
  classname in 'DWScript\Test\SimpleScripts\classname.pas',
  classname_nil_call in 'DWScript\Test\SimpleScripts\classname_nil_call.pas',
  classtype in 'DWScript\Test\SimpleScripts\classtype.pas',
  classtype_nil in 'DWScript\Test\SimpleScripts\classtype_nil.pas',
  clear_ref_in_constructor,
  clear_ref_in_destructor in 'DWScript\Test\SimpleScripts\clear_ref_in_destructor.pas',
  clear_ref_in_static_method in 'DWScript\Test\SimpleScripts\clear_ref_in_static_method.pas',
  clear_ref_in_virtual_method in 'DWScript\Test\SimpleScripts\clear_ref_in_virtual_method.pas',
  coalesce_bool in 'DWScript\Test\SimpleScripts\coalesce_bool.pas',
  coalesce_class in 'DWScript\Test\SimpleScripts\coalesce_class.pas',
  coalesce_class_2 in 'DWScript\Test\SimpleScripts\coalesce_class_2.pas',
  coalesce_dynarray in 'DWScript\Test\SimpleScripts\coalesce_dynarray.pas',
  coalesce_float in 'DWScript\Test\SimpleScripts\coalesce_float.pas',
  coalesce_int in 'DWScript\Test\SimpleScripts\coalesce_int.pas',
  coalesce_string in 'DWScript\Test\SimpleScripts\coalesce_string.pas',
  coalesce_variant in 'DWScript\Test\SimpleScripts\coalesce_variant.pas',
  comments in 'DWScript\Test\SimpleScripts\comments.pas',
  comments_empty in 'DWScript\Test\SimpleScripts\comments_empty.pas',
  compare_bools in 'DWScript\Test\SimpleScripts\compare_bools.pas',
  compare_enumeration in 'DWScript\Test\SimpleScripts\compare_enumeration.pas',
  compare_floats in 'DWScript\Test\SimpleScripts\compare_floats.pas',
  compare_int_zero in 'DWScript\Test\SimpleScripts\compare_int_zero.pas',
  compare_ints in 'DWScript\Test\SimpleScripts\compare_ints.pas',
  compare_ints_table in 'DWScript\Test\SimpleScripts\compare_ints_table.pas',
  compare_strings in 'DWScript\Test\SimpleScripts\compare_strings.pas',
  compare_vars in 'DWScript\Test\SimpleScripts\compare_vars.pas',
  conditionals in 'DWScript\Test\SimpleScripts\conditionals.pas',
  conditionals_else in 'DWScript\Test\SimpleScripts\conditionals_else.pas',
  conditionals_ifndef in 'DWScript\Test\SimpleScripts\conditionals_ifndef.pas',
  conditionals_nested in 'DWScript\Test\SimpleScripts\conditionals_nested.pas',
  conditionals_nested2 in 'DWScript\Test\SimpleScripts\conditionals_nested2.pas',
  conditionals_nested3 in 'DWScript\Test\SimpleScripts\conditionals_nested3.pas',
  conditionals_nested4 in 'DWScript\Test\SimpleScripts\conditionals_nested4.pas',
  const_array_empty in 'DWScript\Test\SimpleScripts\const_array_empty.pas',
  const_array_nested1 in 'DWScript\Test\SimpleScripts\const_array_nested1.pas',
  const_array1 in 'DWScript\Test\SimpleScripts\const_array1.pas',
  const_array2 in 'DWScript\Test\SimpleScripts\const_array2.pas',
  const_array3 in 'DWScript\Test\SimpleScripts\const_array3.pas',
  const_array4 in 'DWScript\Test\SimpleScripts\const_array4.pas',
  const_array5 in 'DWScript\Test\SimpleScripts\const_array5.pas',
  const_array6 in 'DWScript\Test\SimpleScripts\const_array6.pas',
  const_array7 in 'DWScript\Test\SimpleScripts\const_array7.pas',
  const_array8 in 'DWScript\Test\SimpleScripts\const_array8.pas',
  const_block in 'DWScript\Test\SimpleScripts\const_block.pas',
  const_deprecated in 'DWScript\Test\SimpleScripts\const_deprecated.pas',
  const_params1 in 'DWScript\Test\SimpleScripts\const_params1.pas',
  const_params2 in 'DWScript\Test\SimpleScripts\const_params2.pas',
  const_params3 in 'DWScript\Test\SimpleScripts\const_params3.pas',
  const_record in 'DWScript\Test\SimpleScripts\const_record.pas',
  constructor_overload in 'DWScript\Test\SimpleScripts\constructor_overload.pas',
  consts in 'DWScript\Test\SimpleScripts\consts.pas',
  consts_expr in 'DWScript\Test\SimpleScripts\consts_expr.pas',
  contracts_code in 'DWScript\Test\SimpleScripts\contracts_code.pas',
  contracts_old in 'DWScript\Test\SimpleScripts\contracts_old.pas',
  contracts_subproc in 'DWScript\Test\SimpleScripts\contracts_subproc.pas',
  conv_int_float in 'DWScript\Test\SimpleScripts\conv_int_float.pas',
  custom_array_type1 in 'DWScript\Test\SimpleScripts\custom_array_type1.pas',
  declared in 'DWScript\Test\SimpleScripts\declared.pas',
  default_func in 'DWScript\Test\SimpleScripts\default_func.pas',
  default_parameters in 'DWScript\Test\SimpleScripts\default_parameters.pas',
  default_parameters_empty_array in 'DWScript\Test\SimpleScripts\default_parameters_empty_array.pas',
  default_parameters_expr in 'DWScript\Test\SimpleScripts\default_parameters_expr.pas',
  defined in 'DWScript\Test\SimpleScripts\defined.pas',
  destroy in 'DWScript\Test\SimpleScripts\destroy.pas',
  div_by_zero_float in 'DWScript\Test\SimpleScripts\div_by_zero_float.pas',
  div_by_zero_int in 'DWScript\Test\SimpleScripts\div_by_zero_int.pas',
  divide_assign in 'DWScript\Test\SimpleScripts\divide_assign.pas',
  empty_body in 'DWScript\Test\SimpleScripts\empty_body.pas',
  enum_bool_op in 'DWScript\Test\SimpleScripts\enum_bool_op.pas',
  enum_bounds in 'DWScript\Test\SimpleScripts\enum_bounds.pas',
  enum_byname in 'DWScript\Test\SimpleScripts\enum_byname.pas',
  enum_casts in 'DWScript\Test\SimpleScripts\enum_casts.pas',
  enum_const in 'DWScript\Test\SimpleScripts\enum_const.pas',
  enum_element_deprecated in 'DWScript\Test\SimpleScripts\enum_element_deprecated.pas',
  enum_flags1 in 'DWScript\Test\SimpleScripts\enum_flags1.pas',
  enum_scoped in 'DWScript\Test\SimpleScripts\enum_scoped.pas',
  enum_to_integer in 'DWScript\Test\SimpleScripts\enum_to_integer.pas',
  enumerations in 'DWScript\Test\SimpleScripts\enumerations.pas',
  enumerations_names in 'DWScript\Test\SimpleScripts\enumerations_names.pas',
  enumerations_qualifiednames in 'DWScript\Test\SimpleScripts\enumerations_qualifiednames.pas',
  enumerations2 in 'DWScript\Test\SimpleScripts\enumerations2.pas',
  event_virtual in 'DWScript\Test\SimpleScripts\event_virtual.pas',
  exception_log in 'DWScript\Test\SimpleScripts\exception_log.pas',
  exception_nested_call in 'DWScript\Test\SimpleScripts\exception_nested_call.pas',
  exception_nested_call2 in 'DWScript\Test\SimpleScripts\exception_nested_call2.pas',
  exception_scoping in 'DWScript\Test\SimpleScripts\exception_scoping.pas',
  exceptions in 'DWScript\Test\SimpleScripts\exceptions.pas',
  exceptions2 in 'DWScript\Test\SimpleScripts\exceptions2.pas',
  exceptions3 in 'DWScript\Test\SimpleScripts\exceptions3.pas',
  exceptobj in 'DWScript\Test\SimpleScripts\exceptobj.pas',
  exceptobj2 in 'DWScript\Test\SimpleScripts\exceptobj2.pas',
  exceptobj3 in 'DWScript\Test\SimpleScripts\exceptobj3.pas',
  exit in 'DWScript\Test\SimpleScripts\exit.pas',
  exit_case in 'DWScript\Test\SimpleScripts\exit_case.pas',
  exit_constructor in 'DWScript\Test\SimpleScripts\exit_constructor.pas',
  exit_finally in 'DWScript\Test\SimpleScripts\exit_finally.pas',
  exit_finally2 in 'DWScript\Test\SimpleScripts\exit_finally2.pas',
  exit_method_result in 'DWScript\Test\SimpleScripts\exit_method_result.pas',
  exit_result in 'DWScript\Test\SimpleScripts\exit_result.pas',
  exit_result2 in 'DWScript\Test\SimpleScripts\exit_result2.pas',
  external in 'DWScript\Test\SimpleScripts\external.pas',
  field_as_var in 'DWScript\Test\SimpleScripts\field_as_var.pas',
  field_integer_as_float in 'DWScript\Test\SimpleScripts\field_integer_as_float.pas',
  field_scope in 'DWScript\Test\SimpleScripts\field_scope.pas',
  field_typed_default in 'DWScript\Test\SimpleScripts\field_typed_default.pas',
  for_bounds_change in 'DWScript\Test\SimpleScripts\for_bounds_change.pas',
  for_downto_100 in 'DWScript\Test\SimpleScripts\for_downto_100.pas',
  for_in_array in 'DWScript\Test\SimpleScripts\for_in_array.pas',
  for_in_enum in 'DWScript\Test\SimpleScripts\for_in_enum.pas',
  for_in_func_array in 'DWScript\Test\SimpleScripts\for_in_func_array.pas',
  for_in_record_array in 'DWScript\Test\SimpleScripts\for_in_record_array.pas',
  for_in_set in 'DWScript\Test\SimpleScripts\for_in_set.pas',
  for_in_str in 'DWScript\Test\SimpleScripts\for_in_str.pas',
  for_in_str_const in 'DWScript\Test\SimpleScripts\for_in_str_const.pas',
  for_in_str2 in 'DWScript\Test\SimpleScripts\for_in_str2.pas',
  for_in_str3 in 'DWScript\Test\SimpleScripts\for_in_str3.pas',
  for_in_str4 in 'DWScript\Test\SimpleScripts\for_in_str4.pas',
  for_in_subclass in 'DWScript\Test\SimpleScripts\for_in_subclass.pas',
  for_step in 'DWScript\Test\SimpleScripts\for_step.pas',
  for_step_flow in 'DWScript\Test\SimpleScripts\for_step_flow.pas',
  for_step_overflow in 'DWScript\Test\SimpleScripts\for_step_overflow.pas',
  for_step_sign in 'DWScript\Test\SimpleScripts\for_step_sign.pas',
  for_to_100 in 'DWScript\Test\SimpleScripts\for_to_100.pas',
  for_to_variant in 'DWScript\Test\SimpleScripts\for_to_variant.pas',
  for_var_in_array in 'DWScript\Test\SimpleScripts\for_var_in_array.pas',
  for_var_in_enumeration in 'DWScript\Test\SimpleScripts\for_var_in_enumeration.pas',
  for_var_in_field_array in 'DWScript\Test\SimpleScripts\for_var_in_field_array.pas',
  for_var_in_string in 'DWScript\Test\SimpleScripts\for_var_in_string.pas',
  for_var_to1 in 'DWScript\Test\SimpleScripts\for_var_to1.pas',
  format in 'DWScript\Test\SimpleScripts\format.pas',
  format_incorrect_params in 'DWScript\Test\SimpleScripts\format_incorrect_params.pas',
  format2 in 'DWScript\Test\SimpleScripts\format2.pas',
  free_destroy in 'DWScript\Test\SimpleScripts\free_destroy.pas',
  func_inline in 'DWScript\Test\SimpleScripts\func_inline.pas',
  func_nested_in_method in 'DWScript\Test\SimpleScripts\func_nested_in_method.pas',
  func_ptr_assigned in 'DWScript\Test\SimpleScripts\func_ptr_assigned.pas',
  func_ptr_class_meth in 'DWScript\Test\SimpleScripts\func_ptr_class_meth.pas',
  func_ptr_classname in 'DWScript\Test\SimpleScripts\func_ptr_classname.pas',
  func_ptr_constant in 'DWScript\Test\SimpleScripts\func_ptr_constant.pas',
  func_ptr_default in 'DWScript\Test\SimpleScripts\func_ptr_default.pas',
  func_ptr_field in 'DWScript\Test\SimpleScripts\func_ptr_field.pas',
  func_ptr_field_no_param in 'DWScript\Test\SimpleScripts\func_ptr_field_no_param.pas',
  func_ptr_param in 'DWScript\Test\SimpleScripts\func_ptr_param.pas',
  func_ptr_property in 'DWScript\Test\SimpleScripts\func_ptr_property.pas',
  func_ptr_property_alias in 'DWScript\Test\SimpleScripts\func_ptr_property_alias.pas',
  func_ptr_symbol_field in 'DWScript\Test\SimpleScripts\func_ptr_symbol_field.pas',
  func_ptr_var in 'DWScript\Test\SimpleScripts\func_ptr_var.pas',
  func_ptr_var_param in 'DWScript\Test\SimpleScripts\func_ptr_var_param.pas',
  func_ptr1 in 'DWScript\Test\SimpleScripts\func_ptr1.pas',
  func_ptr2 in 'DWScript\Test\SimpleScripts\func_ptr2.pas',
  func_ptr3 in 'DWScript\Test\SimpleScripts\func_ptr3.pas',
  func_ptr4 in 'DWScript\Test\SimpleScripts\func_ptr4.pas',
  func_ptr5 in 'DWScript\Test\SimpleScripts\func_ptr5.pas',
  func_result_as_byref in 'DWScript\Test\SimpleScripts\func_result_as_byref.pas',
  func_subfield in 'DWScript\Test\SimpleScripts\func_subfield.pas',
  heredoc in 'DWScript\Test\SimpleScripts\heredoc.pas',
  heredoc_indent in 'DWScript\Test\SimpleScripts\heredoc_indent.pas',
  heredoc_special in 'DWScript\Test\SimpleScripts\heredoc_special.pas',
  hint_warn in 'DWScript\Test\SimpleScripts\hint_warn.pas',
  if_empty_terms in 'DWScript\Test\SimpleScripts\if_empty_terms.pas',
  ifthenelse_expression_variant in 'DWScript\Test\SimpleScripts\ifthenelse_expression_variant.pas',
  ifthenelse_expression1 in 'DWScript\Test\SimpleScripts\ifthenelse_expression1.pas',
  ifthenelse_expression2 in 'DWScript\Test\SimpleScripts\ifthenelse_expression2.pas',
  ifthenelse_expression3 in 'DWScript\Test\SimpleScripts\ifthenelse_expression3.pas',
  ifthenelse_expression4 in 'DWScript\Test\SimpleScripts\ifthenelse_expression4.pas',
  ifthenelse_expression5 in 'DWScript\Test\SimpleScripts\ifthenelse_expression5.pas',
  ifthenelse_expression6 in 'DWScript\Test\SimpleScripts\ifthenelse_expression6.pas',
  ifthenelse_optimize1 in 'DWScript\Test\SimpleScripts\ifthenelse_optimize1.pas',
  ifthenelse_optimize2 in 'DWScript\Test\SimpleScripts\ifthenelse_optimize2.pas',
  ifthenelse_optimize3 in 'DWScript\Test\SimpleScripts\ifthenelse_optimize3.pas',
  ignore_result in 'DWScript\Test\SimpleScripts\ignore_result.pas',
  implicit_typed_int_to_float in 'DWScript\Test\SimpleScripts\implicit_typed_int_to_float.pas',
  implies in 'DWScript\Test\SimpleScripts\implies.pas',
  in_class_operator in 'DWScript\Test\SimpleScripts\in_class_operator.pas',
  in_integer_operator1 in 'DWScript\Test\SimpleScripts\in_integer_operator1.pas',
  in_integer_operator2 in 'DWScript\Test\SimpleScripts\in_integer_operator2.pas',
  in_operator in 'DWScript\Test\SimpleScripts\in_operator.pas',
  in_string in 'DWScript\Test\SimpleScripts\in_string.pas',
  inc_dec_field in 'DWScript\Test\SimpleScripts\inc_dec_field.pas',
  inc_dec_sideeffect in 'DWScript\Test\SimpleScripts\inc_dec_sideeffect.pas',
  include in 'DWScript\Test\SimpleScripts\include.pas',
  include_expr in 'DWScript\Test\SimpleScripts\include_expr.pas',
  include_once in 'DWScript\Test\SimpleScripts\include_once.pas',
  include_once2 in 'DWScript\Test\SimpleScripts\include_once2.pas',
  includeSym in 'DWScript\Test\SimpleScripts\includeSym.pas',
  index_property in 'DWScript\Test\SimpleScripts\index_property.pas',
  inference1 in 'DWScript\Test\SimpleScripts\inference1.pas',
  inference2 in 'DWScript\Test\SimpleScripts\inference2.pas',
  inherited_constructor in 'DWScript\Test\SimpleScripts\inherited_constructor.pas',
  inherited1 in 'DWScript\Test\SimpleScripts\inherited1.pas',
  inherited2 in 'DWScript\Test\SimpleScripts\inherited2.pas',
  init_dynamic_empty in 'DWScript\Test\SimpleScripts\init_dynamic_empty.pas',
  int_float in 'DWScript\Test\SimpleScripts\int_float.pas',
  int_hex_constant in 'DWScript\Test\SimpleScripts\int_hex_constant.pas',
  lazy in 'DWScript\Test\SimpleScripts\lazy.pas',
  lazy_recursive in 'DWScript\Test\SimpleScripts\lazy_recursive.pas',
  lazy_sqr in 'DWScript\Test\SimpleScripts\lazy_sqr.pas',
  long_name in 'DWScript\Test\SimpleScripts\long_name.pas',
  loop_and_half in 'DWScript\Test\SimpleScripts\loop_and_half.pas',
  loop_over_arrays in 'DWScript\Test\SimpleScripts\loop_over_arrays.pas',
  low_high in 'DWScript\Test\SimpleScripts\low_high.pas',
  meth_ptr1 in 'DWScript\Test\SimpleScripts\meth_ptr1.pas',
  method_condition in 'DWScript\Test\SimpleScripts\method_condition.pas',
  method_contracts in 'DWScript\Test\SimpleScripts\method_contracts.pas',
  method_implem in 'DWScript\Test\SimpleScripts\method_implem.pas',
  method_with_name_of_prop in 'DWScript\Test\SimpleScripts\method_with_name_of_prop.pas',
  method1 in 'DWScript\Test\SimpleScripts\method1.pas',
  minus_assign in 'DWScript\Test\SimpleScripts\minus_assign.pas',
  missing_semicolon in 'DWScript\Test\SimpleScripts\missing_semicolon.pas',
  mixed_nil_array in 'DWScript\Test\SimpleScripts\mixed_nil_array.pas',
  mod_by_zero_int in 'DWScript\Test\SimpleScripts\mod_by_zero_int.pas',
  mod_float in 'DWScript\Test\SimpleScripts\mod_float.pas',
  mod_float_large in 'DWScript\Test\SimpleScripts\mod_float_large.pas',
  modulo in 'DWScript\Test\SimpleScripts\modulo.pas',
  mul_div in 'DWScript\Test\SimpleScripts\mul_div.pas',
  mul_div_optimize in 'DWScript\Test\SimpleScripts\mul_div_optimize.pas',
  mult_assign in 'DWScript\Test\SimpleScripts\mult_assign.pas',
  mult_by2 in 'DWScript\Test\SimpleScripts\mult_by2.pas',
  nested_call in 'DWScript\Test\SimpleScripts\nested_call.pas',
  nested_declarations in 'DWScript\Test\SimpleScripts\nested_declarations.pas',
  new_class_alias in 'DWScript\Test\SimpleScripts\new_class_alias.pas',
  new_class1 in 'DWScript\Test\SimpleScripts\new_class1.pas',
  new_class2 in 'DWScript\Test\SimpleScripts\new_class2.pas',
  new_class3 in 'DWScript\Test\SimpleScripts\new_class3.pas',
  new_class4 in 'DWScript\Test\SimpleScripts\new_class4.pas',
  nil_meta_parameter in 'DWScript\Test\SimpleScripts\nil_meta_parameter.pas',
  not_in_operator in 'DWScript\Test\SimpleScripts\not_in_operator.pas',
  oop in 'DWScript\Test\SimpleScripts\oop.pas',
  oop_compare in 'DWScript\Test\SimpleScripts\oop_compare.pas',
  oop_field in 'DWScript\Test\SimpleScripts\oop_field.pas',
  oop_is_as in 'DWScript\Test\SimpleScripts\oop_is_as.pas',
  open_array_bounds in 'DWScript\Test\SimpleScripts\open_array_bounds.pas',
  open_array1 in 'DWScript\Test\SimpleScripts\open_array1.pas',
  open_array2 in 'DWScript\Test\SimpleScripts\open_array2.pas',
  open_array3 in 'DWScript\Test\SimpleScripts\open_array3.pas',
  operator_precedence1 in 'DWScript\Test\SimpleScripts\operator_precedence1.pas',
  ord in 'DWScript\Test\SimpleScripts\ord.pas',
  ord_bool in 'DWScript\Test\SimpleScripts\ord_bool.pas',
  ord_string_op in 'DWScript\Test\SimpleScripts\ord_string_op.pas',
  ord_surrogate in 'DWScript\Test\SimpleScripts\ord_surrogate.pas',
  override_deep in 'DWScript\Test\SimpleScripts\override_deep.pas',
  params_autocast in 'DWScript\Test\SimpleScripts\params_autocast.pas',
  partial_class_subclass in 'DWScript\Test\SimpleScripts\partial_class_subclass.pas',
  partial_class_unit in 'DWScript\Test\SimpleScripts\partial_class_unit.pas',
  partial_class1 in 'DWScript\Test\SimpleScripts\partial_class1.pas',
  partial_class2 in 'DWScript\Test\SimpleScripts\partial_class2.pas',
  partial_class3 in 'DWScript\Test\SimpleScripts\partial_class3.pas',
  plus_assign in 'DWScript\Test\SimpleScripts\plus_assign.pas',
  plus_plus_minus_minus in 'DWScript\Test\SimpleScripts\plus_plus_minus_minus.pas',
  proc_of_method in 'DWScript\Test\SimpleScripts\proc_of_method.pas',
  procedure_contracts in 'DWScript\Test\SimpleScripts\procedure_contracts.pas',
  program in 'DWScript\Test\SimpleScripts\program.pas',
  programDot in 'DWScript\Test\SimpleScripts\programDot.pas',
  property_call in 'DWScript\Test\SimpleScripts\property_call.pas',
  property_chain in 'DWScript\Test\SimpleScripts\property_chain.pas',
  property_index in 'DWScript\Test\SimpleScripts\property_index.pas',
  property_of_as in 'DWScript\Test\SimpleScripts\property_of_as.pas',
  property_promotion in 'DWScript\Test\SimpleScripts\property_promotion.pas',
  property_reintroduce in 'DWScript\Test\SimpleScripts\property_reintroduce.pas',
  property_sub_default in 'DWScript\Test\SimpleScripts\property_sub_default.pas',
  property_type_array in 'DWScript\Test\SimpleScripts\property_type_array.pas',
  raise_nil in 'DWScript\Test\SimpleScripts\raise_nil.pas',
  re_raise in 'DWScript\Test\SimpleScripts\re_raise.pas',
  readonly_field in 'DWScript\Test\SimpleScripts\readonly_field.pas',
  record_aliased_field in 'DWScript\Test\SimpleScripts\record_aliased_field.pas',
  record_booleans in 'DWScript\Test\SimpleScripts\record_booleans.pas',
  record_class_field_init in 'DWScript\Test\SimpleScripts\record_class_field_init.pas',
  record_clone1 in 'DWScript\Test\SimpleScripts\record_clone1.pas',
  record_const in 'DWScript\Test\SimpleScripts\record_const.pas',
  record_const_as_prop in 'DWScript\Test\SimpleScripts\record_const_as_prop.pas',
  record_dynamic_init in 'DWScript\Test\SimpleScripts\record_dynamic_init.pas',
  record_field_init in 'DWScript\Test\SimpleScripts\record_field_init.pas',
  record_in_copy in 'DWScript\Test\SimpleScripts\record_in_copy.pas',
  record_metaclass_field in 'DWScript\Test\SimpleScripts\record_metaclass_field.pas',
  record_method in 'DWScript\Test\SimpleScripts\record_method.pas',
  record_method_static in 'DWScript\Test\SimpleScripts\record_method_static.pas',
  record_method2 in 'DWScript\Test\SimpleScripts\record_method2.pas',
  record_method3 in 'DWScript\Test\SimpleScripts\record_method3.pas',
  record_method4 in 'DWScript\Test\SimpleScripts\record_method4.pas',
  record_method5 in 'DWScript\Test\SimpleScripts\record_method5.pas',
  record_nested in 'DWScript\Test\SimpleScripts\record_nested.pas',
  record_nested2 in 'DWScript\Test\SimpleScripts\record_nested2.pas',
  record_obj_field in 'DWScript\Test\SimpleScripts\record_obj_field.pas',
  record_passing in 'DWScript\Test\SimpleScripts\record_passing.pas',
  record_passing2 in 'DWScript\Test\SimpleScripts\record_passing2.pas',
  record_passing3 in 'DWScript\Test\SimpleScripts\record_passing3.pas',
  record_passing4 in 'DWScript\Test\SimpleScripts\record_passing4.pas',
  record_property in 'DWScript\Test\SimpleScripts\record_property.pas',
  record_record_field_init in 'DWScript\Test\SimpleScripts\record_record_field_init.pas',
  record_recursive_dynarray in 'DWScript\Test\SimpleScripts\record_recursive_dynarray.pas',
  record_result in 'DWScript\Test\SimpleScripts\record_result.pas',
  record_result2 in 'DWScript\Test\SimpleScripts\record_result2.pas',
  record_result3 in 'DWScript\Test\SimpleScripts\record_result3.pas',
  record_result4 in 'DWScript\Test\SimpleScripts\record_result4.pas',
  record_static_array in 'DWScript\Test\SimpleScripts\record_static_array.pas',
  record_var in 'DWScript\Test\SimpleScripts\record_var.pas',
  record_var_as_prop in 'DWScript\Test\SimpleScripts\record_var_as_prop.pas',
  record_var_param1 in 'DWScript\Test\SimpleScripts\record_var_param1.pas',
  record_var_param2 in 'DWScript\Test\SimpleScripts\record_var_param2.pas',
  recursive_path in 'DWScript\Test\SimpleScripts\recursive_path.pas',
  reintroduce in 'DWScript\Test\SimpleScripts\reintroduce.pas',
  reintroduce_virtual in 'DWScript\Test\SimpleScripts\reintroduce_virtual.pas',
  reserved_word in 'DWScript\Test\SimpleScripts\reserved_word.pas',
  resourcestring1 in 'DWScript\Test\SimpleScripts\resourcestring1.pas',
  result_direct in 'DWScript\Test\SimpleScripts\result_direct.pas',
  result_init in 'DWScript\Test\SimpleScripts\result_init.pas',
  self in 'DWScript\Test\SimpleScripts\self.pas',
  special_chars in 'DWScript\Test\SimpleScripts\special_chars.pas',
  stack_depth in 'DWScript\Test\SimpleScripts\stack_depth.pas',
  stack_of_proc in 'DWScript\Test\SimpleScripts\stack_of_proc.pas',
  stack_peek in 'DWScript\Test\SimpleScripts\stack_peek.pas',
  stacktrace in 'DWScript\Test\SimpleScripts\stacktrace.pas',
  static_array_const in 'DWScript\Test\SimpleScripts\static_array_const.pas',
  static_class in 'DWScript\Test\SimpleScripts\static_class.pas',
  static_class_array in 'DWScript\Test\SimpleScripts\static_class_array.pas',
  static_method1 in 'DWScript\Test\SimpleScripts\static_method1.pas',
  static_method2 in 'DWScript\Test\SimpleScripts\static_method2.pas',
  static_method3 in 'DWScript\Test\SimpleScripts\static_method3.pas',
  static_to_dynamic_empty_array in 'DWScript\Test\SimpleScripts\static_to_dynamic_empty_array.pas',
  string_aggregate in 'DWScript\Test\SimpleScripts\string_aggregate.pas',
  string_array_item_get_set in 'DWScript\Test\SimpleScripts\string_array_item_get_set.pas',
  string_bounds in 'DWScript\Test\SimpleScripts\string_bounds.pas',
  string_bounds2 in 'DWScript\Test\SimpleScripts\string_bounds2.pas',
  string_builtin_methods in 'DWScript\Test\SimpleScripts\string_builtin_methods.pas',
  string_class_field_get_set in 'DWScript\Test\SimpleScripts\string_class_field_get_set.pas',
  string_compare in 'DWScript\Test\SimpleScripts\string_compare.pas',
  string_in_op in 'DWScript\Test\SimpleScripts\string_in_op.pas',
  string_in_op2 in 'DWScript\Test\SimpleScripts\string_in_op2.pas',
  string_in_op3 in 'DWScript\Test\SimpleScripts\string_in_op3.pas',
  string_manip in 'DWScript\Test\SimpleScripts\string_manip.pas',
  string_quotes in 'DWScript\Test\SimpleScripts\string_quotes.pas',
  string_record_field_get_set in 'DWScript\Test\SimpleScripts\string_record_field_get_set.pas',
  string_static_access in 'DWScript\Test\SimpleScripts\string_static_access.pas',
  swap_record in 'DWScript\Test\SimpleScripts\swap_record.pas',
  swap_static_array in 'DWScript\Test\SimpleScripts\swap_static_array.pas',
  swap1 in 'DWScript\Test\SimpleScripts\swap1.pas',
  swap2 in 'DWScript\Test\SimpleScripts\swap2.pas',
  triple_apos1 in 'DWScript\Test\SimpleScripts\triple_apos1.pas',
  triple_apos2 in 'DWScript\Test\SimpleScripts\triple_apos2.pas',
  try_except_finally in 'DWScript\Test\SimpleScripts\try_except_finally.pas',
  unicode_const in 'DWScript\Test\SimpleScripts\unicode_const.pas',
  unicode_identifiers in 'DWScript\Test\SimpleScripts\unicode_identifiers.pas',
  unicode_print in 'DWScript\Test\SimpleScripts\unicode_print.pas',
  value_type_separation in 'DWScript\Test\SimpleScripts\value_type_separation.pas',
  var_eq_nil in 'DWScript\Test\SimpleScripts\var_eq_nil.pas',
  var_nan in 'DWScript\Test\SimpleScripts\var_nan.pas',
  var_param_casts in 'DWScript\Test\SimpleScripts\var_param_casts.pas',
  var_param_nested in 'DWScript\Test\SimpleScripts\var_param_nested.pas',
  var_param_obj_method in 'DWScript\Test\SimpleScripts\var_param_obj_method.pas',
  var_param_parent in 'DWScript\Test\SimpleScripts\var_param_parent.pas',
  var_param_rec_field in 'DWScript\Test\SimpleScripts\var_param_rec_field.pas',
  var_param_rec_method in 'DWScript\Test\SimpleScripts\var_param_rec_method.pas',
  var_param_record in 'DWScript\Test\SimpleScripts\var_param_record.pas',
  variable_initialization in 'DWScript\Test\SimpleScripts\variable_initialization.pas',
  variable_initialization2 in 'DWScript\Test\SimpleScripts\variable_initialization2.pas',
  variant_compound_ops in 'DWScript\Test\SimpleScripts\variant_compound_ops.pas',
  variant_logical_ops in 'DWScript\Test\SimpleScripts\variant_logical_ops.pas',
  variant_ops in 'DWScript\Test\SimpleScripts\variant_ops.pas',
  variant_unassigned_equal in 'DWScript\Test\SimpleScripts\variant_unassigned_equal.pas',
  variants in 'DWScript\Test\SimpleScripts\variants.pas',
  variants_as_casts in 'DWScript\Test\SimpleScripts\variants_as_casts.pas',
  variants_binary_bool_int in 'DWScript\Test\SimpleScripts\variants_binary_bool_int.pas',
  variants_bool in 'DWScript\Test\SimpleScripts\variants_bool.pas',
  variants_casts in 'DWScript\Test\SimpleScripts\variants_casts.pas',
  variants_explicit_casts in 'DWScript\Test\SimpleScripts\variants_explicit_casts.pas',
  variants_is_bool in 'DWScript\Test\SimpleScripts\variants_is_bool.pas',
  variants_strict in 'DWScript\Test\SimpleScripts\variants_strict.pas',
  virtual_constructor in 'DWScript\Test\SimpleScripts\virtual_constructor.pas',
  virtual_constructor2 in 'DWScript\Test\SimpleScripts\virtual_constructor2.pas',
  while_true in 'DWScript\Test\SimpleScripts\while_true.pas',
  with1 in 'DWScript\Test\SimpleScripts\with1.pas';

uses
  System.SysUtils,
  System.Types,
  IPPeerServer,
  IPPeerAPI,
  IdHTTPWebBrokerBridge,
  Web.WebReq,
  Web.WebBroker,
  WebModuleUnit1 in 'WebModuleUnit1.pas' {WebModule1: TWebModule},
  PSPEngine in 'PSPEngine.pas',
  PSPParser in 'src\PSPParser.pas',
  dwsComp in 'DWScript\Source\dwsComp.pas',
  dwsArrayElementContext in 'DWScript\Source\dwsArrayElementContext.pas',
  dwsArrayExprs in 'DWScript\Source\dwsArrayExprs.pas',
  dwsArrayIndexOfExprs in 'DWScript\Source\dwsArrayIndexOfExprs.pas',
  dwsArrayMethodKinds in 'DWScript\Source\dwsArrayMethodKinds.pas',
  dwsAssociativeArrays in 'DWScript\Source\dwsAssociativeArrays.pas',
  dwsComConnector in 'DWScript\Source\dwsComConnector.pas',
  dwsCompilerContext in 'DWScript\Source\dwsCompilerContext.pas',
  dwsCompilerUtils in 'DWScript\Source\dwsCompilerUtils.pas',
  dwsConnectorExprs in 'DWScript\Source\dwsConnectorExprs.pas',
  dwsConnectorSymbols in 'DWScript\Source\dwsConnectorSymbols.pas',
  dwsConstExprs in 'DWScript\Source\dwsConstExprs.pas',
  dwsContextMap in 'DWScript\Source\dwsContextMap.pas',
  dwsConvExprs in 'DWScript\Source\dwsConvExprs.pas',
  dwsCoreExprs in 'DWScript\Source\dwsCoreExprs.pas',
  dwsCryptoXPlatform in 'DWScript\Source\dwsCryptoXPlatform.pas',
  dwsCustomData in 'DWScript\Source\dwsCustomData.pas',
  dwsDataContext in 'DWScript\Source\dwsDataContext.pas',
  dwsDateTime in 'DWScript\Source\dwsDateTime.pas',
  dwsDebugFunctions in 'DWScript\Source\dwsDebugFunctions.pas',
  dwsDebugger in 'DWScript\Source\dwsDebugger.pas',
  dwsDynamicArrays in 'DWScript\Source\dwsDynamicArrays.pas',
  dwsEncoding in 'DWScript\Source\dwsEncoding.pas',
  dwsErrors in 'DWScript\Source\dwsErrors.pas',
  dwsEvaluate in 'DWScript\Source\dwsEvaluate.pas',
  dwsExperts in 'DWScript\Source\dwsExperts.pas',
  dwsExprList in 'DWScript\Source\dwsExprList.pas',
  dwsExprs in 'DWScript\Source\dwsExprs.pas',
  dwsExternalFunctions in 'DWScript\Source\dwsExternalFunctions.pas',
  dwsExternalSymbols in 'DWScript\Source\dwsExternalSymbols.pas',
  dwsFileFunctions in 'DWScript\Source\dwsFileFunctions.pas',
  dwsFileSystem in 'DWScript\Source\dwsFileSystem.pas',
  dwsFilter in 'DWScript\Source\dwsFilter.pas',
  dwsCompiler in 'DWScript\Source\dwsCompiler.pas',
  dwsUtils in 'DWScript\Source\dwsUtils.pas',
  dwsXPlatform in 'DWScript\Source\dwsXPlatform.pas',
  dwsStrings in 'DWScript\Source\dwsStrings.pas',
  dwsXXHash in 'DWScript\Source\dwsXXHash.pas',
  Wcrypt2 in 'DWScript\Source\Wcrypt2.pas',
  dwsFunctions in 'DWScript\Source\dwsFunctions.pas',
  dwsSymbols in 'DWScript\Source\dwsSymbols.pas',
  DelegateTestLibModule in 'DWScript\Test\DelegateTestLibModule.pas' {DelegateTestLib: TDataModule},
  dwsXPlatformTests in 'DWScript\Test\dwsXPlatformTests.pas',
  LanguageTestsLAZ in 'DWScript\Test\LanguageTestsLAZ.pas',
  UAlgorithmsTests in 'DWScript\Test\UAlgorithmsTests.pas',
  UAutoFormatTests in 'DWScript\Test\UAutoFormatTests.pas',
  UBigIntegerTests in 'DWScript\Test\UBigIntegerTests.pas',
  UBuildTests in 'DWScript\Test\UBuildTests.pas',
  UCodeDOMTests in 'DWScript\Test\UCodeDOMTests.pas',
  UCOMConnectorTests in 'DWScript\Test\UCOMConnectorTests.pas',
  UCornerCasesTests in 'DWScript\Test\UCornerCasesTests.pas',
  UDebuggerTests in 'DWScript\Test\UDebuggerTests.pas',
  UdwsClassesTests in 'DWScript\Test\UdwsClassesTests.pas',
  UdwsCryptoTests in 'DWScript\Test\UdwsCryptoTests.pas',
  UdwsCSSPackTests in 'DWScript\Test\UdwsCSSPackTests.pas',
  UdwsCustomDataTests in 'DWScript\Test\UdwsCustomDataTests.pas',
  UdwsDataBaseTests in 'DWScript\Test\UdwsDataBaseTests.pas',
  UdwsDateTimeTests in 'DWScript\Test\UdwsDateTimeTests.pas',
  UdwsEncodingTests in 'DWScript\Test\UdwsEncodingTests.pas',
  UdwsFunctionsTests in 'DWScript\Test\UdwsFunctionsTests.pas',
  UdwsGraphicsTests in 'DWScript\Test\UdwsGraphicsTests.pas',
  UdwsIniFileTests in 'DWScript\Test\UdwsIniFileTests.pas',
  UdwsSystemInfoTests in 'DWScript\Test\UdwsSystemInfoTests.pas',
  UdwsTabularTests in 'DWScript\Test\UdwsTabularTests.pas',
  UdwsTimeSeriesTests in 'DWScript\Test\UdwsTimeSeriesTests.pas',
  UdwsUnitTests in 'DWScript\Test\UdwsUnitTests.pas',
  UdwsUnitTestsStatic in 'DWScript\Test\UdwsUnitTestsStatic.pas',
  UdwsUtilsTests in 'DWScript\Test\UdwsUtilsTests.pas',
  UdwsWebLibModuleTest in 'DWScript\Test\UdwsWebLibModuleTest.pas',
  UdwsWebUtilsTests in 'DWScript\Test\UdwsWebUtilsTests.pas',
  UdwsXPlatformTests in 'DWScript\Test\UdwsXPlatformTests.pas',
  UExternalFunctionTests in 'DWScript\Test\UExternalFunctionTests.pas',
  UHTMLFilterTests in 'DWScript\Test\UHTMLFilterTests.pas',
  UInstantiateTests in 'DWScript\Test\UInstantiateTests.pas',
  UJITTests in 'DWScript\Test\UJITTests.pas',
  UJITx86_64Tests in 'DWScript\Test\UJITx86_64Tests.pas',
  UJITx86Tests in 'DWScript\Test\UJITx86Tests.pas',
  UJSCodeGenTests in 'DWScript\Test\UJSCodeGenTests.pas',
  UJSFilterTests in 'DWScript\Test\UJSFilterTests.pas',
  UJSONConnectorTests in 'DWScript\Test\UJSONConnectorTests.pas',
  UJSONTests in 'DWScript\Test\UJSONTests.pas',
  UJSSmartLinkerTests in 'DWScript\Test\UJSSmartLinkerTests.pas',
  UJSTestChromium in 'DWScript\Test\UJSTestChromium.pas',
  ULanguageExtensionTests in 'DWScript\Test\ULanguageExtensionTests.pas',
  ULinqJsonTests in 'DWScript\Test\ULinqJsonTests.pas',
  ULinqTests in 'DWScript\Test\ULinqTests.pas',
  ULocalizerTests in 'DWScript\Test\ULocalizerTests.pas',
  UMemoryTests in 'DWScript\Test\UMemoryTests.pas',
  URTTIExposeTests in 'DWScript\Test\URTTIExposeTests.pas',
  UScriptTests in 'DWScript\Test\UScriptTests.pas',
  USourceUtilsTests in 'DWScript\Test\USourceUtilsTests.pas',
  USpecialTestsRTTI in 'DWScript\Test\USpecialTestsRTTI.pas',
  USymbolDictionaryTests in 'DWScript\Test\USymbolDictionaryTests.pas',
  UTestDispatcher in 'DWScript\Test\UTestDispatcher.pas',
  UTokenizerTests in 'DWScript\Test\UTokenizerTests.pas',
  gethostbyaddr in 'DWScript\Test\WebLib\gethostbyaddr.pas',
  gethostbyname in 'DWScript\Test\WebLib\gethostbyname.pas',
  webrequest in 'DWScript\Test\WebLib\webrequest.pas',
  basic_unnamed in 'DWScript\Test\TimeSeriesLib\basic_unnamed.pas',
  nans in 'DWScript\Test\TimeSeriesLib\nans.pas',
  next in 'DWScript\Test\TimeSeriesLib\next.pas',
  ranges in 'DWScript\Test\TimeSeriesLib\ranges.pas',
  rounding in 'DWScript\Test\TimeSeriesLib\rounding.pas',
  basic_batch in 'DWScript\Test\TabularLib\basic_batch.pas',
  basic_cmp_jit in 'DWScript\Test\TabularLib\basic_cmp_jit.pas',
  basic_cmp_nojit in 'DWScript\Test\TabularLib\basic_cmp_nojit.pas',
  basic_columns in 'DWScript\Test\TabularLib\basic_columns.pas',
  basic_manyops in 'DWScript\Test\TabularLib\basic_manyops.pas',
  basic_ops_jit in 'DWScript\Test\TabularLib\basic_ops_jit.pas',
  basic_ops_nojit in 'DWScript\Test\TabularLib\basic_ops_nojit.pas',
  dup in 'DWScript\Test\TabularLib\dup.pas',
  evaluate_columns in 'DWScript\Test\TabularLib\evaluate_columns.pas',
  lookup_stress in 'DWScript\Test\TabularLib\lookup_stress.pas',
  lookupfield in 'DWScript\Test\TabularLib\lookupfield.pas',
  newcolumns_compute in 'DWScript\Test\TabularLib\newcolumns_compute.pas',
  numfield_default in 'DWScript\Test\TabularLib\numfield_default.pas',
  numfielddef_stress in 'DWScript\Test\TabularLib\numfielddef_stress.pas',
  round_floor_ceil in 'DWScript\Test\TabularLib\round_floor_ceil.pas',
  smape in 'DWScript\Test\TabularLib\smape.pas',
  appinfo in 'DWScript\Test\SystemInfoLib\appinfo.pas',
  memory in 'DWScript\Test\SystemInfoLib\memory.pas',
  registry in 'DWScript\Test\SystemInfoLib\registry.pas',
  ackermann in 'DWScript\Test\SimpleScripts\ackermann.pas',
  aliased_enum in 'DWScript\Test\SimpleScripts\aliased_enum.pas',
  aliased_float in 'DWScript\Test\SimpleScripts\aliased_float.pas',
  aliased_vs_nil in 'DWScript\Test\SimpleScripts\aliased_vs_nil.pas',
  alphanum in 'DWScript\Test\SimpleScripts\alphanum.pas',
  arithmetic in 'DWScript\Test\SimpleScripts\arithmetic.pas',
  arithmetic_div in 'DWScript\Test\SimpleScripts\arithmetic_div.pas',
  assert in 'DWScript\Test\SimpleScripts\assert.pas',
  assert_variant in 'DWScript\Test\SimpleScripts\assert_variant.pas',
  assigned in 'DWScript\Test\SimpleScripts\assigned.pas',
  assigned_funcresult in 'DWScript\Test\SimpleScripts\assigned_funcresult.pas',
  assignments in 'DWScript\Test\SimpleScripts\assignments.pas',
  binary_literal in 'DWScript\Test\SimpleScripts\binary_literal.pas',
  bitwise in 'DWScript\Test\SimpleScripts\bitwise.pas',
  bitwise_sar in 'DWScript\Test\SimpleScripts\bitwise_sar.pas',
  bitwise_shifts in 'DWScript\Test\SimpleScripts\bitwise_shifts.pas',
  bool_combos in 'DWScript\Test\SimpleScripts\bool_combos.pas',
  bool_string in 'DWScript\Test\SimpleScripts\bool_string.pas',
  bool_xor in 'DWScript\Test\SimpleScripts\bool_xor.pas',
  boolean_and in 'DWScript\Test\SimpleScripts\boolean_and.pas',
  boolean_array_of in 'DWScript\Test\SimpleScripts\boolean_array_of.pas',
  boolean_is in 'DWScript\Test\SimpleScripts\boolean_is.pas',
  boolean_optimize in 'DWScript\Test\SimpleScripts\boolean_optimize.pas',
  boolean_or in 'DWScript\Test\SimpleScripts\boolean_or.pas',
  booleans in 'DWScript\Test\SimpleScripts\booleans.pas',
  break_continue in 'DWScript\Test\SimpleScripts\break_continue.pas',
  break_in_except_block in 'DWScript\Test\SimpleScripts\break_in_except_block.pas',
  call_conventions in 'DWScript\Test\SimpleScripts\call_conventions.pas',
  case,
  case_boolean in 'DWScript\Test\SimpleScripts\case_boolean.pas',
  case_break in 'DWScript\Test\SimpleScripts\case_break.pas',
  case_range in 'DWScript\Test\SimpleScripts\case_range.pas',
  case_variant in 'DWScript\Test\SimpleScripts\case_variant.pas',
  case_variant_condition in 'DWScript\Test\SimpleScripts\case_variant_condition.pas',
  casts_base_types in 'DWScript\Test\SimpleScripts\casts_base_types.pas',
  char_in in 'DWScript\Test\SimpleScripts\char_in.pas',
  chinese in 'DWScript\Test\SimpleScripts\chinese.pas',
  class_abstract_method in 'DWScript\Test\SimpleScripts\class_abstract_method.pas',
  class_cast in 'DWScript\Test\SimpleScripts\class_cast.pas',
  class_cast_meta in 'DWScript\Test\SimpleScripts\class_cast_meta.pas',
  class_const in 'DWScript\Test\SimpleScripts\class_const.pas',
  class_const_as_prop in 'DWScript\Test\SimpleScripts\class_const_as_prop.pas',
  class_const2 in 'DWScript\Test\SimpleScripts\class_const2.pas',
  class_const3 in 'DWScript\Test\SimpleScripts\class_const3.pas',
  class_const4 in 'DWScript\Test\SimpleScripts\class_const4.pas',
  class_forward in 'DWScript\Test\SimpleScripts\class_forward.pas',
  class_init in 'DWScript\Test\SimpleScripts\class_init.pas',
  class_inline_declared in 'DWScript\Test\SimpleScripts\class_inline_declared.pas',
  class_method in 'DWScript\Test\SimpleScripts\class_method.pas',
  class_method2 in 'DWScript\Test\SimpleScripts\class_method2.pas',
  class_method3 in 'DWScript\Test\SimpleScripts\class_method3.pas',
  class_method4 in 'DWScript\Test\SimpleScripts\class_method4.pas',
  class_of in 'DWScript\Test\SimpleScripts\class_of.pas',
  class_of_cast in 'DWScript\Test\SimpleScripts\class_of_cast.pas',
  class_of2 in 'DWScript\Test\SimpleScripts\class_of2.pas',
  class_of3 in 'DWScript\Test\SimpleScripts\class_of3.pas',
  class_operator1 in 'DWScript\Test\SimpleScripts\class_operator1.pas',
  class_operator2 in 'DWScript\Test\SimpleScripts\class_operator2.pas',
  class_operator3 in 'DWScript\Test\SimpleScripts\class_operator3.pas',
  class_parent in 'DWScript\Test\SimpleScripts\class_parent.pas',
  class_property in 'DWScript\Test\SimpleScripts\class_property.pas',
  class_scoping1 in 'DWScript\Test\SimpleScripts\class_scoping1.pas',
  class_self in 'DWScript\Test\SimpleScripts\class_self.pas',
  class_selfref in 'DWScript\Test\SimpleScripts\class_selfref.pas',
  class_var in 'DWScript\Test\SimpleScripts\class_var.pas',
  class_var_as_prop in 'DWScript\Test\SimpleScripts\class_var_as_prop.pas',
  class_var_dyn1 in 'DWScript\Test\SimpleScripts\class_var_dyn1.pas',
  class_var_dyn2 in 'DWScript\Test\SimpleScripts\class_var_dyn2.pas',
  classname in 'DWScript\Test\SimpleScripts\classname.pas',
  classname_nil_call in 'DWScript\Test\SimpleScripts\classname_nil_call.pas',
  classtype in 'DWScript\Test\SimpleScripts\classtype.pas',
  classtype_nil in 'DWScript\Test\SimpleScripts\classtype_nil.pas',
  clear_ref_in_constructor assignment in 'DWScript\Test\SimpleScripts\clear_ref_in_constructor assignment.pas';

uses
  System.SysUtils,
  System.Types,
  IPPeerServer,
  IPPeerAPI,
  IdHTTPWebBrokerBridge,
  Web.WebReq,
  Web.WebBroker,
  WebModuleUnit1 in 'WebModuleUnit1.pas' {WebModule1: TWebModule},
  PSPEngine in 'PSPEngine.pas',
  PSPParser in 'src\PSPParser.pas',
  dwsComp in 'DWScript\Source\dwsComp.pas',
  dwsArrayElementContext in 'DWScript\Source\dwsArrayElementContext.pas',
  dwsArrayExprs in 'DWScript\Source\dwsArrayExprs.pas',
  dwsArrayIndexOfExprs in 'DWScript\Source\dwsArrayIndexOfExprs.pas',
  dwsArrayMethodKinds in 'DWScript\Source\dwsArrayMethodKinds.pas',
  dwsAssociativeArrays in 'DWScript\Source\dwsAssociativeArrays.pas',
  dwsComConnector in 'DWScript\Source\dwsComConnector.pas',
  dwsCompilerContext in 'DWScript\Source\dwsCompilerContext.pas',
  dwsCompilerUtils in 'DWScript\Source\dwsCompilerUtils.pas',
  dwsConnectorExprs in 'DWScript\Source\dwsConnectorExprs.pas',
  dwsConnectorSymbols in 'DWScript\Source\dwsConnectorSymbols.pas',
  dwsConstExprs in 'DWScript\Source\dwsConstExprs.pas',
  dwsContextMap in 'DWScript\Source\dwsContextMap.pas',
  dwsConvExprs in 'DWScript\Source\dwsConvExprs.pas',
  dwsCoreExprs in 'DWScript\Source\dwsCoreExprs.pas',
  dwsCryptoXPlatform in 'DWScript\Source\dwsCryptoXPlatform.pas',
  dwsCustomData in 'DWScript\Source\dwsCustomData.pas',
  dwsDataContext in 'DWScript\Source\dwsDataContext.pas',
  dwsDateTime in 'DWScript\Source\dwsDateTime.pas',
  dwsDebugFunctions in 'DWScript\Source\dwsDebugFunctions.pas',
  dwsDebugger in 'DWScript\Source\dwsDebugger.pas',
  dwsDynamicArrays in 'DWScript\Source\dwsDynamicArrays.pas',
  dwsEncoding in 'DWScript\Source\dwsEncoding.pas',
  dwsErrors in 'DWScript\Source\dwsErrors.pas',
  dwsEvaluate in 'DWScript\Source\dwsEvaluate.pas',
  dwsExperts in 'DWScript\Source\dwsExperts.pas',
  dwsExprList in 'DWScript\Source\dwsExprList.pas',
  dwsExprs in 'DWScript\Source\dwsExprs.pas',
  dwsExternalFunctions in 'DWScript\Source\dwsExternalFunctions.pas',
  dwsExternalSymbols in 'DWScript\Source\dwsExternalSymbols.pas',
  dwsFileFunctions in 'DWScript\Source\dwsFileFunctions.pas',
  dwsFileSystem in 'DWScript\Source\dwsFileSystem.pas',
  dwsFilter in 'DWScript\Source\dwsFilter.pas',
  dwsCompiler in 'DWScript\Source\dwsCompiler.pas',
  dwsUtils in 'DWScript\Source\dwsUtils.pas',
  dwsXPlatform in 'DWScript\Source\dwsXPlatform.pas',
  dwsStrings in 'DWScript\Source\dwsStrings.pas',
  dwsXXHash in 'DWScript\Source\dwsXXHash.pas',
  Wcrypt2 in 'DWScript\Source\Wcrypt2.pas',
  dwsFunctions in 'DWScript\Source\dwsFunctions.pas',
  dwsSymbols in 'DWScript\Source\dwsSymbols.pas',
  DelegateTestLibModule in 'DWScript\Test\DelegateTestLibModule.pas' {DelegateTestLib: TDataModule},
  dwsXPlatformTests in 'DWScript\Test\dwsXPlatformTests.pas',
  LanguageTestsLAZ in 'DWScript\Test\LanguageTestsLAZ.pas',
  UAlgorithmsTests in 'DWScript\Test\UAlgorithmsTests.pas',
  UAutoFormatTests in 'DWScript\Test\UAutoFormatTests.pas',
  UBigIntegerTests in 'DWScript\Test\UBigIntegerTests.pas',
  UBuildTests in 'DWScript\Test\UBuildTests.pas',
  UCodeDOMTests in 'DWScript\Test\UCodeDOMTests.pas',
  UCOMConnectorTests in 'DWScript\Test\UCOMConnectorTests.pas',
  UCornerCasesTests in 'DWScript\Test\UCornerCasesTests.pas',
  UDebuggerTests in 'DWScript\Test\UDebuggerTests.pas',
  UdwsClassesTests in 'DWScript\Test\UdwsClassesTests.pas',
  UdwsCryptoTests in 'DWScript\Test\UdwsCryptoTests.pas',
  UdwsCSSPackTests in 'DWScript\Test\UdwsCSSPackTests.pas',
  UdwsCustomDataTests in 'DWScript\Test\UdwsCustomDataTests.pas',
  UdwsDataBaseTests in 'DWScript\Test\UdwsDataBaseTests.pas',
  UdwsDateTimeTests in 'DWScript\Test\UdwsDateTimeTests.pas',
  UdwsEncodingTests in 'DWScript\Test\UdwsEncodingTests.pas',
  UdwsFunctionsTests in 'DWScript\Test\UdwsFunctionsTests.pas',
  UdwsGraphicsTests in 'DWScript\Test\UdwsGraphicsTests.pas',
  UdwsIniFileTests in 'DWScript\Test\UdwsIniFileTests.pas',
  UdwsSystemInfoTests in 'DWScript\Test\UdwsSystemInfoTests.pas',
  UdwsTabularTests in 'DWScript\Test\UdwsTabularTests.pas',
  UdwsTimeSeriesTests in 'DWScript\Test\UdwsTimeSeriesTests.pas',
  UdwsUnitTests in 'DWScript\Test\UdwsUnitTests.pas',
  UdwsUnitTestsStatic in 'DWScript\Test\UdwsUnitTestsStatic.pas',
  UdwsUtilsTests in 'DWScript\Test\UdwsUtilsTests.pas',
  UdwsWebLibModuleTest in 'DWScript\Test\UdwsWebLibModuleTest.pas',
  UdwsWebUtilsTests in 'DWScript\Test\UdwsWebUtilsTests.pas',
  UdwsXPlatformTests in 'DWScript\Test\UdwsXPlatformTests.pas',
  UExternalFunctionTests in 'DWScript\Test\UExternalFunctionTests.pas',
  UHTMLFilterTests in 'DWScript\Test\UHTMLFilterTests.pas',
  UInstantiateTests in 'DWScript\Test\UInstantiateTests.pas',
  UJITTests in 'DWScript\Test\UJITTests.pas',
  UJITx86_64Tests in 'DWScript\Test\UJITx86_64Tests.pas',
  UJITx86Tests in 'DWScript\Test\UJITx86Tests.pas',
  UJSCodeGenTests in 'DWScript\Test\UJSCodeGenTests.pas',
  UJSFilterTests in 'DWScript\Test\UJSFilterTests.pas',
  UJSONConnectorTests in 'DWScript\Test\UJSONConnectorTests.pas',
  UJSONTests in 'DWScript\Test\UJSONTests.pas',
  UJSSmartLinkerTests in 'DWScript\Test\UJSSmartLinkerTests.pas',
  UJSTestChromium in 'DWScript\Test\UJSTestChromium.pas',
  ULanguageExtensionTests in 'DWScript\Test\ULanguageExtensionTests.pas',
  ULinqJsonTests in 'DWScript\Test\ULinqJsonTests.pas',
  ULinqTests in 'DWScript\Test\ULinqTests.pas',
  ULocalizerTests in 'DWScript\Test\ULocalizerTests.pas',
  UMemoryTests in 'DWScript\Test\UMemoryTests.pas',
  URTTIExposeTests in 'DWScript\Test\URTTIExposeTests.pas',
  UScriptTests in 'DWScript\Test\UScriptTests.pas',
  USourceUtilsTests in 'DWScript\Test\USourceUtilsTests.pas',
  USpecialTestsRTTI in 'DWScript\Test\USpecialTestsRTTI.pas',
  USymbolDictionaryTests in 'DWScript\Test\USymbolDictionaryTests.pas',
  UTestDispatcher in 'DWScript\Test\UTestDispatcher.pas',
  UTokenizerTests in 'DWScript\Test\UTokenizerTests.pas',
  gethostbyaddr in 'DWScript\Test\WebLib\gethostbyaddr.pas',
  gethostbyname in 'DWScript\Test\WebLib\gethostbyname.pas',
  webrequest in 'DWScript\Test\WebLib\webrequest.pas',
  basic_unnamed in 'DWScript\Test\TimeSeriesLib\basic_unnamed.pas',
  nans in 'DWScript\Test\TimeSeriesLib\nans.pas',
  next in 'DWScript\Test\TimeSeriesLib\next.pas',
  ranges in 'DWScript\Test\TimeSeriesLib\ranges.pas',
  rounding in 'DWScript\Test\TimeSeriesLib\rounding.pas',
  basic_batch in 'DWScript\Test\TabularLib\basic_batch.pas',
  basic_cmp_jit in 'DWScript\Test\TabularLib\basic_cmp_jit.pas',
  basic_cmp_nojit in 'DWScript\Test\TabularLib\basic_cmp_nojit.pas',
  basic_columns in 'DWScript\Test\TabularLib\basic_columns.pas',
  basic_manyops in 'DWScript\Test\TabularLib\basic_manyops.pas',
  basic_ops_jit in 'DWScript\Test\TabularLib\basic_ops_jit.pas',
  basic_ops_nojit in 'DWScript\Test\TabularLib\basic_ops_nojit.pas',
  dup in 'DWScript\Test\TabularLib\dup.pas',
  evaluate_columns in 'DWScript\Test\TabularLib\evaluate_columns.pas',
  lookup_stress in 'DWScript\Test\TabularLib\lookup_stress.pas',
  lookupfield in 'DWScript\Test\TabularLib\lookupfield.pas',
  newcolumns_compute in 'DWScript\Test\TabularLib\newcolumns_compute.pas',
  numfield_default in 'DWScript\Test\TabularLib\numfield_default.pas',
  numfielddef_stress in 'DWScript\Test\TabularLib\numfielddef_stress.pas',
  round_floor_ceil in 'DWScript\Test\TabularLib\round_floor_ceil.pas',
  smape in 'DWScript\Test\TabularLib\smape.pas',
  appinfo in 'DWScript\Test\SystemInfoLib\appinfo.pas',
  memory in 'DWScript\Test\SystemInfoLib\memory.pas',
  registry in 'DWScript\Test\SystemInfoLib\registry.pas',
  ackermann in 'DWScript\Test\SimpleScripts\ackermann.pas',
  aliased_enum in 'DWScript\Test\SimpleScripts\aliased_enum.pas',
  aliased_float in 'DWScript\Test\SimpleScripts\aliased_float.pas',
  aliased_vs_nil in 'DWScript\Test\SimpleScripts\aliased_vs_nil.pas',
  alphanum in 'DWScript\Test\SimpleScripts\alphanum.pas',
  arithmetic in 'DWScript\Test\SimpleScripts\arithmetic.pas',
  arithmetic_div in 'DWScript\Test\SimpleScripts\arithmetic_div.pas',
  assert in 'DWScript\Test\SimpleScripts\assert.pas',
  assert_variant in 'DWScript\Test\SimpleScripts\assert_variant.pas',
  assigned in 'DWScript\Test\SimpleScripts\assigned.pas',
  assigned_funcresult in 'DWScript\Test\SimpleScripts\assigned_funcresult.pas',
  assignments in 'DWScript\Test\SimpleScripts\assignments.pas',
  binary_literal in 'DWScript\Test\SimpleScripts\binary_literal.pas',
  bitwise in 'DWScript\Test\SimpleScripts\bitwise.pas',
  bitwise_sar in 'DWScript\Test\SimpleScripts\bitwise_sar.pas',
  bitwise_shifts in 'DWScript\Test\SimpleScripts\bitwise_shifts.pas',
  bool_combos in 'DWScript\Test\SimpleScripts\bool_combos.pas',
  bool_string in 'DWScript\Test\SimpleScripts\bool_string.pas',
  bool_xor in 'DWScript\Test\SimpleScripts\bool_xor.pas',
  boolean_and in 'DWScript\Test\SimpleScripts\boolean_and.pas',
  boolean_array_of in 'DWScript\Test\SimpleScripts\boolean_array_of.pas',
  boolean_is in 'DWScript\Test\SimpleScripts\boolean_is.pas',
  boolean_optimize in 'DWScript\Test\SimpleScripts\boolean_optimize.pas',
  boolean_or in 'DWScript\Test\SimpleScripts\boolean_or.pas',
  booleans in 'DWScript\Test\SimpleScripts\booleans.pas',
  break_continue in 'DWScript\Test\SimpleScripts\break_continue.pas',
  break_in_except_block in 'DWScript\Test\SimpleScripts\break_in_except_block.pas',
  call_conventions in 'DWScript\Test\SimpleScripts\call_conventions.pas',
  case statement in 'DWScript\Test\SimpleScripts\case statement.pas';

{$R *.res}

function BindPort(APort: Integer): Boolean;
var
  LTestServer: IIPTestServer;
begin
  Result := True;
  try
    LTestServer := PeerFactory.CreatePeer('', IIPTestServer) as IIPTestServer;
    LTestServer.TestOpenPort(APort, nil);
  except
    Result := False;
  end;
end;

function CheckPort(APort: Integer): Integer;
begin
  if BindPort(APort) then
    Result := APort
  else
    Result := 0;
end;

procedure SetPort(const AServer: TIdHTTPWebBrokerBridge; APort: String);
begin
  if not AServer.Active then
  begin
    APort := APort.Replace(cCommandSetPort, '').Trim;
    if CheckPort(APort.ToInteger) > 0 then
    begin
      AServer.DefaultPort := APort.ToInteger;
      Writeln(Format(sPortSet, [APort]));
    end
    else
      Writeln(Format(sPortInUse, [APort]));
  end
  else
    Writeln(sServerRunning);
  Write(cArrow);
end;

procedure StartServer(const AServer: TIdHTTPWebBrokerBridge);
begin
  if not AServer.Active then
  begin
    if CheckPort(AServer.DefaultPort) > 0 then
    begin
      Writeln(Format(sStartingServer, [AServer.DefaultPort]));
      AServer.Bindings.Clear;
      AServer.Active := True;
    end
    else
      Writeln(Format(sPortInUse, [AServer.DefaultPort.ToString]));
  end
  else
    Writeln(sServerRunning);
  Write(cArrow);
end;

procedure StopServer(const AServer: TIdHTTPWebBrokerBridge);
begin
  if AServer.Active then
  begin
    Writeln(sStoppingServer);
    AServer.Active := False;
    AServer.Bindings.Clear;
    Writeln(sServerStopped);
  end
  else
    Writeln(sServerNotRunning);
  Write(cArrow);
end;

procedure WriteCommands;
begin
  Writeln(sCommands);
  Write(cArrow);
end;

procedure WriteStatus(const AServer: TIdHTTPWebBrokerBridge);
begin
  Writeln(sIndyVersion + AServer.SessionList.Version);
  Writeln(sActive + AServer.Active.ToString(TUseBoolStrs.True));
  Writeln(sPort + AServer.DefaultPort.ToString);
  Writeln(sSessionID + AServer.SessionIDCookieName);
  Write(cArrow);
end;

procedure RunServer(APort: Integer);
var
  LServer: TIdHTTPWebBrokerBridge;
  LResponse: string;
begin
  WriteCommands;
  LServer := TIdHTTPWebBrokerBridge.Create(nil);
  try
    LServer.DefaultPort := APort;
    while True do
    begin
      Readln(LResponse);
      LResponse := LowerCase(LResponse);
      if LResponse.StartsWith(cCommandSetPort) then
        SetPort(LServer, LResponse)
      else if sametext(LResponse, cCommandStart) then
        StartServer(LServer)
      else if sametext(LResponse, cCommandStatus) then
        WriteStatus(LServer)
      else if sametext(LResponse, cCommandStop) then
        StopServer(LServer)
      else if sametext(LResponse, cCommandHelp) then
        WriteCommands
      else if sametext(LResponse, cCommandExit) then
        if LServer.Active then
        begin
          StopServer(LServer);
          break
        end
        else
          break
      else
      begin
        Writeln(sInvalidCommand);
        Write(cArrow);
      end;
    end;
  finally
    LServer.Free;
  end;
end;

begin
  try
    if WebRequestHandler <> nil then
      WebRequestHandler.WebModuleClass := WebModuleClass;
    RunServer(8080);
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end

end.
