name: Mirror from Bitbucket

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4

      - name: Clone from Bitbucket using Repo Token
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --mirror https://x-token-auth:${{ secrets.BB_REPO_TOKEN }}@bitbucket.org/rainsoftworks/pascalserverpages.git bb-mirror
          cd bb-mirror
      - name: Push to GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd bb-mirror
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push --mirror
